### PR TITLE
Adding ROS-2 rolling CI to the repository and some changes to have it working.

### PR DESCRIPTION
**Pull request by olivier-stasse**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."
This pull request provides  a github action to test the repository on ROS-2 rolling.
It provides the necessary changes on package.xml to have the upward dependencies installed on the docker.

## How I Tested

[//]: # "Explain how you tested your changes"
Tests are compiled and run directly in the CI now.
One on Nan had to be commented because it is  failing.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [X] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).  Comment: no c++ and no python code had to be changed.
- [X] All new functions/classes are documented and existing documentation is updated according to changes.
- [X] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

Comments:
Maybe the ```find_package(Python)``` is not needed and could be removed. But I would like to have feedback on this PR to move forward the release of the package on ROS-2.

### CODE REVIEW

**Review by nim65s — COMMENTED** [review]
I don't understand the changes in sdk/master_board_sdk/CMakeLists.txt. Are they required ? What problem are you trying to solve ?

**Comment by olivier-stasse** [comment]
> I don't understand the changes in sdk/master_board_sdk/CMakeLists.txt. Are they required ? What problem are you trying to solve ?

Probably not. The package.xml dependencies are needed to install python3-dev and libboost-python in the ros-industrial-ci. But I did modify CMakeLists.txt before finding the solution. I will try to revert the modifications on CMakeLists.txt and if it works I will push it in this PR.

**Comment by olivier-stasse** [comment]
The problem I am trying to solve is to have the ros-industrial-ci works on this repository.
We would have this kind of results, needed for a release on ros-2 distribution:
https://github.com/olivier-stasse/master-board/actions/runs/5119920070/jobs/9205779140

And normally I put back the CMakeLists.txt file to its initial situation but now with the tests running in the docker (and with cache).

**Review by nim65s — APPROVED** [review]

**Comment by thomasfla** [comment]
Thanks

**Pull request merged**
