### PR TITLE
Use mailbox for SPI communication

### PR DESCRIPTION
**Pull request by jviereck**
This is a cherry-pick from #107 to improve the SPI communication.

In contrast to #107, this PR only contains the changes to use a mailbox for SPI communicaiton and no other changes.

This PR was NOT yet tested on hardware.

### CODE REVIEW

**Comment by jviereck** [comment]
@luator , can you try to build and test this version of the code? Especially, if there are SPI problems and if the IMU is working as expected (sending useful data at 1000 kHz). I don't have access to hardware anymore, but if you need any help like writing a small test program or similar, let me know.

Best,
Julian

**Comment by luator** [comment]
I tested with my adapted version of example_pd and it seemed to be good.  I monitored the SPI communication of one uDriver for around a minute and there were zero broken packets (i.e. CRC always good).  IMU values are provided and they look reasonable.

There was a weird issue that when running for the first time after power-on, it would fail with a timeout but I had the same today with the master branch so probably not related to the changes here (I'm using wifi which is anyway a bit unreliable).

I'm a bit busy today, if you have time to write some test application to check the IMU frequency, that would be great.  Otherwise I can look into it next week.

**Comment by jviereck** [comment]
Thanks for testing this branch!

> I'm a bit busy today, if you have time to write some test application to check the IMU frequency, that would be great. Otherwise I can look into it next week.

I've pushed some code. There is a new executeable `example_imu_data_collection.cpp`. Once you run it, it should collect data from the IMU for 10 seconds. Then, the executeable shuts down and dumps the data as csv. There is also a new python script to load the csv data and create plots from it.

The python script generates two plots: One plot showing all the data and one plot showing the last 30 ms of the recorded data. The idea is that the second plot allows you to see if the IMU holds the last value or it changes at 1 kHz.

I haven't tested the code / it might not compile. I hope you can fix it though.

Let me know if you need anything else

**Comment by luator** [comment]
Thanks, there were some compiler errors but easy to fix.  I ran it and recorded some data:
[example_imu_all_data.pdf](https://github.com/open-dynamic-robot-initiative/master-board/files/8756169/example_imu_all_data.pdf)
[example_imu_last_few_data.pdf](https://github.com/open-dynamic-robot-initiative/master-board/files/8756170/example_imu_last_few_data.pdf)
[imu_data_collection.csv](https://github.com/open-dynamic-robot-initiative/master-board/files/8756172/imu_data_collection.csv)

It seems that accelerometer and gyroscope are updated in every step but attitude and linear_acceleration only every two steps.  Is this expected?

**Comment by thomasfla** [comment]
Thanks!
Yes, this is expected. All the EKF data should be at 500Hz (maximum data rate).

**Review by luator — APPROVED** [review]

**Comment by jviereck** [comment]
I merged this to master.

@thomasfla Do you want to send a message to the ODRI forum to let people know about this improvement / recommending them to reflash the master board? If you want I can send such a message.

**Pull request merged**
