### PR TITLE
Set close to zero velocity to zero. Fixes #92

### LINKED ISSUE #92: Problem with velocity from micro drivers
As reported by @wxmerkt in #89:

> When standing perfectly still (zero-order hold), we have been seeing (1) significant outliers in the velocity signal (that are different from the position signal going to zero when the SPI frequency is too high) and (2) non-zero velocity even when the joint isn't moving (the raw uint is 1 and never decrements below).
>
> For (1), we are using filtering that includes outlier rejection and this works well. For (2), this issue impacts state estimation quite a bit and we have a work-around that if the uint is 1, we consider it to be 0. Those two changes made state estimation quite stable.

We should look into this and try to fix it on the firmware level (either master board or udrivers).

### PR DESCRIPTION
**Pull request by jviereck**
Printing the velocity values while the robot is at rest, I was getting these readings:

```
motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = 0.000000

motor_drivers[i].motor1->velocity = -0.051133
motor_drivers[i].motor2->velocity = -0.051133

motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = -0.051133

motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = 0.000000

motor_drivers[i].motor1->velocity = -0.051133
motor_drivers[i].motor2->velocity = -0.051133

motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = -0.051133

motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = 0.000000

motor_drivers[i].motor1->velocity = -0.051133
motor_drivers[i].motor2->velocity = -0.051133

motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = -0.051133

motor_drivers[i].motor1->velocity = 0.000000
motor_drivers[i].motor2->velocity = 0.000000
```

Based on this, I set the velocity to zero if it's below 0.052 on both motors.

### CODE REVIEW

**Comment by jviereck** [comment]
\cc @wxmerkt

**Comment by thomasfla** [comment]
Thanks for this PR.

Alternatively, the fix could be done before the packet interpretation: 
https://github.com/open-dynamic-robot-initiative/master-board/blob/1c81a2acbfd44f1c25f5ebe23487057b9e6cf7f8/sdk/master_board_sdk/src/master_board_interface.cpp#L362
by comparing sensor_packet.dual_motor_driver_sensor_packets[i].velocity[x] with +1 and -1.

```
if (sensor_packet.dual_motor_driver_sensor_packets[i].velocity[x] == 1 || 
    sensor_packet.dual_motor_driver_sensor_packets[i].velocity[x] == -1) 
{
    sensor_packet.dual_motor_driver_sensor_packets[i].velocity[x]  = 0;
}
```

This way, we don't have to hard-code the threshold, and it will automatically adapt to a any future change of velocity resolution.

**Comment by wxmerkt** [comment]
Thanks @jviereck! I truncate on the output side after the 9:1 if it's below 0.006 which translates to 0.054 - so this does the same job :-).

**Comment by jviereck** [comment]
> Alternatively, the fix could be done before the packet interpretation:

Thanks for the suggestion @thomasfla . I've updated the PR accordingly.

Can people take a second look and if this is good I will merge the PR.

**Review by MaximilienNaveau — APPROVED** [review]
Sounds good to me,
Does it solve your issue?

**Comment by thomasfla** [comment]
Thanks!

**Comment by jviereck** [comment]
> Does it solve your issue?

Yes. I tested it on the real solo12 and it removes the steady-state velocity-off-by-one problem reported initially by @wxmerkt .

**Pull request merged**
