### PR TITLE
Make communication more robust

### PR DESCRIPTION
**Pull request by jviereck**
While testing our solo12 in New York I noticed that error 15 / 0xf was showing up from time to time (in the order of 100 times per 30 seconds). This happened on the front stack where we use 30 cm long cables for the SPI connection. 

Looking at the master board code, it looks like this error is reported when the SPI communication was not proper. See the code at [1].

To work around this, I increased the number of SPI_N_ATTEMPT in the firmware configuration. After increasing the number from 2 to three attempts, the communication is stable at zero errors.

To visualize this problem, I've extended the `example.cpp` example. It now has a counter for the number of times an error was reported at the motor drivers.

[1]: https://github.com/open-dynamic-robot-initiative/master-board/blob/master/firmware/main/masterboard_main.c#L319

### CODE REVIEW

**Comment by jviereck** [comment]
@thomasfla do you have an idea if increasing the number of attempts to three will cause troubles with the communication / timing? How high can this number go?

**Comment by jviereck** [comment]
Turns out the problem with the reported error `15` persists. I am not sure if increasing the `SPI_N_ATTEMPT` further is a good idea. I will try to make new wires and solve the issue by fixing the hardware instead...

**Comment by jviereck** [comment]
I reverted the change about the `SPI_N_ATEMPT` and lowered the value back to `2` again in this PR.

I keep the PR open as the new reporting of number of errors seen so far seems useful to have by default in the example app.

**Comment by thomasfla** [comment]
Hi @jviereck Unfortunately the SPI issue might come from either noise on the SPI lines, or from the uDrivers themselves, indeed the SPI interrupt can be ignored during critical portion of the code. This is a MCU limitation, and it will be fixed with the next release of the motor driver hardware "omodri". Increasing the SPI_N_ATEMPT can help. Having it too large can compromise the loop time on the master board.

**Comment by jviereck** [comment]
Hi @thomasfla , thanks for your reply. 

I tried to increase the SPI_N_ATEMPT but was still getting single errors after some time. What I've done now is to reduce the SPI speed from 6 Mhz to 4 Mhz. With this I am able to have a stable communication with still keeping SPI_N_ATEMPT=1.

As for this PR, are you fine to add the counting of errors in the example.cpp?

**Comment by MaximilienNaveau** [comment]
@thomasfla should we merge this?

**Comment by MaximilienNaveau** [comment]
I approve this PR this is just about the example.cpp anyway and it's nice to have error feedback

**Pull request merged**
